config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :vehicle_ownerships

      resources :favorites

      resources :vehicle_types

      resources :reviews

      resources :reservations

      resources :garages

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "garages#index"
  resources :vehicle_ownerships
  resources :favorites
  resources :vehicle_types
  resources :reviews
  resources :reservations
  resources :garages
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vehicle_ownership.rb
class VehicleOwnership < ApplicationRecord
  # Direct associations

  belongs_to :vehicle_type,
             foreign_key: "vehicle_id"

  belongs_to :owner,
             class_name: "User"

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    vehicle_type.to_s
  end
end

app/controllers/api/v1/vehicle_ownerships_controller.rb
class Api::V1::VehicleOwnershipsController < Api::V1::GraphitiController
  def index
    vehicle_ownerships = VehicleOwnershipResource.all(params)
    respond_with(vehicle_ownerships)
  end

  def show
    vehicle_ownership = VehicleOwnershipResource.find(params)
    respond_with(vehicle_ownership)
  end

  def create
    vehicle_ownership = VehicleOwnershipResource.build(params)

    if vehicle_ownership.save
      render jsonapi: vehicle_ownership, status: :created
    else
      render jsonapi_errors: vehicle_ownership
    end
  end

  def update
    vehicle_ownership = VehicleOwnershipResource.find(params)

    if vehicle_ownership.update_attributes
      render jsonapi: vehicle_ownership
    else
      render jsonapi_errors: vehicle_ownership
    end
  end

  def destroy
    vehicle_ownership = VehicleOwnershipResource.find(params)

    if vehicle_ownership.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: vehicle_ownership
    end
  end
end

app/controllers/vehicle_ownerships_controller.rb
class VehicleOwnershipsController < ApplicationController
  before_action :set_vehicle_ownership, only: %i[show edit update destroy]

  def index
    @q = VehicleOwnership.ransack(params[:q])
    @vehicle_ownerships = @q.result(distinct: true).includes(:owner,
                                                             :vehicle_type).page(params[:page]).per(10)
  end

  def show; end

  def new
    @vehicle_ownership = VehicleOwnership.new
  end

  def edit; end

  def create
    @vehicle_ownership = VehicleOwnership.new(vehicle_ownership_params)

    if @vehicle_ownership.save
      message = "VehicleOwnership was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @vehicle_ownership, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @vehicle_ownership.update(vehicle_ownership_params)
      redirect_to @vehicle_ownership,
                  notice: "Vehicle ownership was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @vehicle_ownership.destroy
    message = "VehicleOwnership was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to vehicle_ownerships_url, notice: message
    end
  end

  private

  def set_vehicle_ownership
    @vehicle_ownership = VehicleOwnership.find(params[:id])
  end

  def vehicle_ownership_params
    params.require(:vehicle_ownership).permit(:vehicle_id, :owner_id,
                                              :license_plate_number)
  end
end

app/views/vehicle_ownerships/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Vehicle Ownership #<%= vehicle_ownership.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Vehicle</dt>
      <dd>
        <% if @vehicle_ownership.vehicle_type.present? %>
          <%= link_to vehicle_ownership.vehicle_type, vehicle_ownership.vehicle_type %>
        <% end %>
      </dd>

      <dt>Owner</dt>
      <dd>
        <% if @vehicle_ownership.owner.present? %>
          <%= link_to vehicle_ownership.owner, vehicle_ownership.owner %>
        <% end %>
      </dd>

      <dt>License plate number</dt>
      <dd><%= vehicle_ownership.license_plate_number %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back vehicle_ownership, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_vehicle_ownership_url(vehicle_ownership), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to vehicle_ownership, method: :delete, data: { confirm: "Do you really want to delete this vehicle_ownership?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(vehicle_ownership.updated_at) %> ago
  </div>
</div>

app/views/vehicle_ownerships/_form.html.erb
<% was_validated = vehicle_ownership.errors.any? %>

<%= form_with(model: vehicle_ownership, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% vehicle_class = "form-control" %>
    <% vehicle_was_invalid = vehicle_ownership.errors.include?(:vehicle) %>

    <% if was_validated %>
      <% if vehicle_was_invalid %>
        <% vehicle_class << " is-invalid" %>
      <% else %>
        <% vehicle_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :vehicle_id %>
    <%= f.collection_select :vehicle_id, VehicleType.all, :id, :to_s, {}, class: "form-control" %>
    <% if vehicle_was_invalid %>
      <% vehicle_ownership.errors.full_messages_for(:vehicle).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% owner_class = "form-control" %>
    <% owner_was_invalid = vehicle_ownership.errors.include?(:owner) %>

    <% if was_validated %>
      <% if owner_was_invalid %>
        <% owner_class << " is-invalid" %>
      <% else %>
        <% owner_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :owner_id %>
    <%= f.collection_select :owner_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if owner_was_invalid %>
      <% vehicle_ownership.errors.full_messages_for(:owner).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% license_plate_number_class = "form-control" %>
    <% license_plate_number_was_invalid = vehicle_ownership.errors.include?(:license_plate_number) %>

    <% if was_validated %>
      <% if license_plate_number_was_invalid %>
        <% license_plate_number_class << " is-invalid" %>
      <% else %>
        <% license_plate_number_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :license_plate_number %>
    <%= f.text_field :license_plate_number, class: license_plate_number_class, placeholder: "Enter license plate number" %>
    <% if license_plate_number_was_invalid %>
      <% vehicle_ownership.errors.full_messages_for(:license_plate_number).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/vehicle_ownerships/_list_item.html.erb
<%= link_to vehicle_ownership, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= vehicle_ownership %>
    <small class="text-muted">
      <%= time_ago_in_words(vehicle_ownership.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/vehicle_ownerships/_vehicle_ownerships_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "vehicle_ownerships_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :license_plate_number_cont, "License plate number contains" %>
    <%= f.text_field :license_plate_number_cont, :class => "form-control", :placeholder => "License plate number contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :owner_email_cont, "Owner email contains" %>
    <%= f.text_field :owner_email_cont, :class => "form-control", :placeholder => "Owner email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :vehicle_type_make_cont, "Vehicle type make contains" %>
    <%= f.text_field :vehicle_type_make_cont, :class => "form-control", :placeholder => "Vehicle type make contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/vehicle_ownerships" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#vehicle_ownerships_filters">
  Show filters
</a>

app/views/vehicle_ownerships/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Vehicle Ownership #<%= @vehicle_ownership.id %>
      </h2>

      <div class="card-body">
        <%= render "form", vehicle_ownership: @vehicle_ownership %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/vehicle_ownerships/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Vehicle Ownerships

      <%= link_to new_vehicle_ownership_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "vehicle_ownerships/vehicle_ownerships_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Vehicle Ownerships

        <%= link_to new_vehicle_ownership_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @vehicle_ownerships, partial: "list_item", as: :vehicle_ownership %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @vehicle_ownerships, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/vehicle_ownerships/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Vehicle Ownership
      </h2>

      <div class="card-body">
        <%= render "form", vehicle_ownership: @vehicle_ownership %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/vehicle_ownerships/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @vehicle_ownership, partial: "card", as: :vehicle_ownership %>
  </div>
</div>