config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :vehicle_ownerships

      resources :favorites

      resources :vehicle_types

      resources :reviews

      resources :reservations

      resources :garages

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "garages#index"
  resources :vehicle_ownerships
  resources :favorites
  resources :vehicle_types
  resources :reviews
  resources :reservations
  resources :garages
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  # Direct associations

  belongs_to :garage

  belongs_to :user

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    user.to_s
  end
end

app/controllers/api/v1/favorites_controller.rb
class Api::V1::FavoritesController < Api::V1::GraphitiController
  def index
    favorites = FavoriteResource.all(params)
    respond_with(favorites)
  end

  def show
    favorite = FavoriteResource.find(params)
    respond_with(favorite)
  end

  def create
    favorite = FavoriteResource.build(params)

    if favorite.save
      render jsonapi: favorite, status: :created
    else
      render jsonapi_errors: favorite
    end
  end

  def update
    favorite = FavoriteResource.find(params)

    if favorite.update_attributes
      render jsonapi: favorite
    else
      render jsonapi_errors: favorite
    end
  end

  def destroy
    favorite = FavoriteResource.find(params)

    if favorite.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: favorite
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: %i[show edit update destroy]

  def index
    @q = Favorite.ransack(params[:q])
    @favorites = @q.result(distinct: true).includes(:user,
                                                    :garage).page(params[:page]).per(10)
  end

  def show; end

  def new
    @favorite = Favorite.new
  end

  def edit; end

  def create
    @favorite = Favorite.new(favorite_params)

    if @favorite.save
      message = "Favorite was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @favorite, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @favorite.update(favorite_params)
      redirect_to @favorite, notice: "Favorite was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @favorite.destroy
    message = "Favorite was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to favorites_url, notice: message
    end
  end

  private

  def set_favorite
    @favorite = Favorite.find(params[:id])
  end

  def favorite_params
    params.require(:favorite).permit(:user_id, :garage_id)
  end
end

app/views/favorites/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Favorite #<%= favorite.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>User</dt>
      <dd>
        <% if @favorite.user.present? %>
          <%= link_to favorite.user, favorite.user %>
        <% end %>
      </dd>

      <dt>Garage</dt>
      <dd>
        <% if @favorite.garage.present? %>
          <%= link_to favorite.garage, favorite.garage %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back favorite, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_favorite_url(favorite), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to favorite, method: :delete, data: { confirm: "Do you really want to delete this favorite?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(favorite.updated_at) %> ago
  </div>
</div>

app/views/favorites/_favorites_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "favorites_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :user_email_cont, "User email contains" %>
    <%= f.text_field :user_email_cont, :class => "form-control", :placeholder => "User email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :garage_garage_name_cont, "Garage garage_name contains" %>
    <%= f.text_field :garage_garage_name_cont, :class => "form-control", :placeholder => "Garage garage_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/favorites" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#favorites_filters">
  Show filters
</a>

app/views/favorites/_form.html.erb
<% was_validated = favorite.errors.any? %>

<%= form_with(model: favorite, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% user_class = "form-control" %>
    <% user_was_invalid = favorite.errors.include?(:user) %>

    <% if was_validated %>
      <% if user_was_invalid %>
        <% user_class << " is-invalid" %>
      <% else %>
        <% user_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if user_was_invalid %>
      <% favorite.errors.full_messages_for(:user).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% garage_class = "form-control" %>
    <% garage_was_invalid = favorite.errors.include?(:garage) %>

    <% if was_validated %>
      <% if garage_was_invalid %>
        <% garage_class << " is-invalid" %>
      <% else %>
        <% garage_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :garage_id %>
    <%= f.collection_select :garage_id, Garage.all, :id, :to_s, {}, class: "form-control" %>
    <% if garage_was_invalid %>
      <% favorite.errors.full_messages_for(:garage).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/favorites/_list_item.html.erb
<%= link_to favorite, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= favorite %>
    <small class="text-muted">
      <%= time_ago_in_words(favorite.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/favorites/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Favorite #<%= @favorite.id %>
      </h2>

      <div class="card-body">
        <%= render "form", favorite: @favorite %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Favorites

      <%= link_to new_favorite_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "favorites/favorites_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Favorites

        <%= link_to new_favorite_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @favorites, partial: "list_item", as: :favorite %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @favorites, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/favorites/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Favorite
      </h2>

      <div class="card-body">
        <%= render "form", favorite: @favorite %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @favorite, partial: "card", as: :favorite %>
  </div>
</div>