config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :vehicle_ownerships

      resources :favorites

      resources :vehicle_types

      resources :reviews

      resources :reservations

      resources :garages

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "garages#index"
  resources :vehicle_ownerships
  resources :favorites
  resources :vehicle_types
  resources :reviews
  resources :reservations
  resources :garages
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/vehicle_types_controller.rb
class Api::V1::VehicleTypesController < Api::V1::GraphitiController
  def index
    vehicle_types = VehicleTypeResource.all(params)
    respond_with(vehicle_types)
  end

  def show
    vehicle_type = VehicleTypeResource.find(params)
    respond_with(vehicle_type)
  end

  def create
    vehicle_type = VehicleTypeResource.build(params)

    if vehicle_type.save
      render jsonapi: vehicle_type, status: :created
    else
      render jsonapi_errors: vehicle_type
    end
  end

  def update
    vehicle_type = VehicleTypeResource.find(params)

    if vehicle_type.update_attributes
      render jsonapi: vehicle_type
    else
      render jsonapi_errors: vehicle_type
    end
  end

  def destroy
    vehicle_type = VehicleTypeResource.find(params)

    if vehicle_type.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: vehicle_type
    end
  end
end

app/controllers/vehicle_types_controller.rb
class VehicleTypesController < ApplicationController
  before_action :set_vehicle_type, only: %i[show edit update destroy]

  def index
    @q = VehicleType.ransack(params[:q])
    @vehicle_types = @q.result(distinct: true).includes(:owners).page(params[:page]).per(10)
  end

  def show
    @vehicle_ownership = VehicleOwnership.new
  end

  def new
    @vehicle_type = VehicleType.new
  end

  def edit; end

  def create
    @vehicle_type = VehicleType.new(vehicle_type_params)

    if @vehicle_type.save
      redirect_to @vehicle_type,
                  notice: "Vehicle type was successfully created."
    else
      render :new
    end
  end

  def update
    if @vehicle_type.update(vehicle_type_params)
      redirect_to @vehicle_type,
                  notice: "Vehicle type was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @vehicle_type.destroy
    redirect_to vehicle_types_url,
                notice: "Vehicle type was successfully destroyed."
  end

  private

  def set_vehicle_type
    @vehicle_type = VehicleType.find(params[:id])
  end

  def vehicle_type_params
    params.require(:vehicle_type).permit(:make, :model, :width, :height)
  end
end

app/views/vehicle_types/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Vehicle Type #<%= vehicle_type.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Make</dt>
      <dd><%= vehicle_type.make %></dd>

      <dt>Model</dt>
      <dd><%= vehicle_type.model %></dd>

      <dt>Width</dt>
      <dd><%= vehicle_type.width %></dd>

      <dt>Height</dt>
      <dd><%= vehicle_type.height %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back vehicle_type, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_vehicle_type_url(vehicle_type), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to vehicle_type, method: :delete, data: { confirm: "Do you really want to delete this vehicle_type?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(vehicle_type.updated_at) %> ago
  </div>
</div>

app/views/vehicle_types/_form.html.erb
<% was_validated = vehicle_type.errors.any? %>

<%= form_with(model: vehicle_type, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% make_class = "form-control" %>
    <% make_was_invalid = vehicle_type.errors.include?(:make) %>

    <% if was_validated %>
      <% if make_was_invalid %>
        <% make_class << " is-invalid" %>
      <% else %>
        <% make_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :make %>
    <%= f.text_field :make, class: make_class, placeholder: "Enter make" %>
    <% if make_was_invalid %>
      <% vehicle_type.errors.full_messages_for(:make).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% model_class = "form-control" %>
    <% model_was_invalid = vehicle_type.errors.include?(:model) %>

    <% if was_validated %>
      <% if model_was_invalid %>
        <% model_class << " is-invalid" %>
      <% else %>
        <% model_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :model %>
    <%= f.text_field :model, class: model_class, placeholder: "Enter model" %>
    <% if model_was_invalid %>
      <% vehicle_type.errors.full_messages_for(:model).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% width_class = "form-control" %>
    <% width_was_invalid = vehicle_type.errors.include?(:width) %>

    <% if was_validated %>
      <% if width_was_invalid %>
        <% width_class << " is-invalid" %>
      <% else %>
        <% width_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :width %>
    <%= f.text_field :width, class: width_class, placeholder: "Enter width" %>
    <% if width_was_invalid %>
      <% vehicle_type.errors.full_messages_for(:width).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% height_class = "form-control" %>
    <% height_was_invalid = vehicle_type.errors.include?(:height) %>

    <% if was_validated %>
      <% if height_was_invalid %>
        <% height_class << " is-invalid" %>
      <% else %>
        <% height_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :height %>
    <%= f.text_field :height, class: height_class, placeholder: "Enter height" %>
    <% if height_was_invalid %>
      <% vehicle_type.errors.full_messages_for(:height).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/vehicle_types/_list_item.html.erb
<%= link_to vehicle_type, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= vehicle_type %>
    <small class="text-muted">
      <%= time_ago_in_words(vehicle_type.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/vehicle_types/_vehicle_type_owners.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Owners

    <a data-toggle="collapse" href="#vehicle_type_owners_new_form">
      Add vehicle ownership
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @vehicle_type.owners.each do |vehicle_ownership| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to vehicle_ownership, vehicle_ownership %>

        <%= link_to vehicle_ownership, method: :delete, data: { confirm: "Do you really want to delete this vehicle_ownership" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="vehicle_type_owners_new_form">
        <%= render partial: "vehicle_types/vehicle_type_owners_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/vehicle_types/_vehicle_type_owners_new_form.html.erb
<%= form_with(model: @vehicle_ownership, local: true) do |f| %>

  <%= f.hidden_field :vehicle_id, value: @vehicle_type.id %>

  <div class="form-group">
    <%= f.label :owner_id %>

    <%= f.collection_select :owner_id, User.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :license_plate_number %>

    <%= f.text_field :license_plate_number, class: "form-control" %>
  </div>

  <%= f.submit "Create vehicle ownership", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/vehicle_types/_vehicle_types_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "vehicle_types_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :make_cont, "Make contains" %>
    <%= f.text_field :make_cont, :class => "form-control", :placeholder => "Make contains" %>
  </div>

  <div class="form-group">
    <%= f.label :height, "Height" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :height_gteq, :class => "form-control", :placeholder => "Height greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :height_lteq, :class => "form-control", :placeholder => "Height less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :width, "Width" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :width_gteq, :class => "form-control", :placeholder => "Width greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :width_lteq, :class => "form-control", :placeholder => "Width less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :model_cont, "Model contains" %>
    <%= f.text_field :model_cont, :class => "form-control", :placeholder => "Model contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>




  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/vehicle_types" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#vehicle_types_filters">
  Show filters
</a>

app/views/vehicle_types/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Vehicle Type #<%= @vehicle_type.id %>
      </h2>

      <div class="card-body">
        <%= render "form", vehicle_type: @vehicle_type %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/vehicle_types/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Vehicle Types

      <%= link_to new_vehicle_type_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "vehicle_types/vehicle_types_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Vehicle Types

        <%= link_to new_vehicle_type_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @vehicle_types, partial: "list_item", as: :vehicle_type %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @vehicle_types, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/vehicle_types/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Vehicle Type
      </h2>

      <div class="card-body">
        <%= render "form", vehicle_type: @vehicle_type %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/vehicle_types/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @vehicle_type, partial: "card", as: :vehicle_type %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "vehicle_types/vehicle_type_owners" %>
  </div>
</div>